development:
  adapter: postgresql
  encoding: unicode
  database: sparklr_development

test:
  adapter: postgresql
  encoding: unicode
  database: sparklr_test

production:
  adapter: postgresql
  encoding: unicode
  database: sparklr_production
